#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=81
STOP=01
 
CONFIGURATION="usbipd"

callback(){
        config_get usbid "$1" "usbid"

        busid="$(usbip list -p -l | grep "#usbid=$usbid#" | cut '-d#' -f1)"

        if [ ! -n "$busid" ]; then
                return
        fi

        usbip $2 --$busid
}

stop_service(){
	config_load "${CONFIGURATION}"
	config_foreach callback device unbind
}

start_service(){
        config_load "${CONFIGURATION}"
        config_foreach callback device bind

	procd_open_instance
	procd_set_param command sleep infinity
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_close_instance
}
