#!/bin/sh /etc/rc.common
 
USE_PROCD=1
 
START=81
STOP=01
 
CONFIGURATION="usbipd"

unbind(){
	config="$1"
	config_get usbid "$config" "usbid"

	busid="$(usbip list -p -l | grep "#usbid=$usbid#" | cut '-d#' -f1)"

	if [ ! -n "$busid" ]; then
		return
	fi

	usbip unbind --$busid
}

bind(){
	config="$1"
	config_get usbid "$config" "usbid"

	procd_open_instance
	procd_set_param command /usr/sbin/usbip-bind $usbid
    procd_set_param stdout 1
    procd_set_param stderr 1
	procd_close_instance
}

stop_service(){
	config_load "${CONFIGURATION}"
	config_foreach unbind device
}

start_service(){
	config_load "${CONFIGURATION}"
	config_foreach bind device
}
